config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|it/ do
    resources :categories
    devise_for :users
    resources :listings do
      resources :orders, only: [:new, :create]
    end
    get 'pages/about'

    get 'pages/contact'
    get 'seller' => "listings#seller"
    get 'sales' => "orders#sales"
    get 'purchases' => "orders#purchases"
    root 'listings#index'

  end

end

app/views/layouts/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<%= image_tag("happy_footer.png") %>
<footer><p>&copy; 2016 Organicmarketplace.com, Inc. All rights reserved.</p></footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "OrganicMarketplace", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to t('navbar.about'), pages_about_path %></li>
        <li><%= link_to t('navbar.contact'), pages_contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
             aria-expanded="false"><%= t('navbar.language') %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <li><%= link_to t('navbar.english'), root_path(locale: 'en') %></li>
            <li><%= link_to t('navbar.italian'), root_path(locale: 'it') %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
             aria-expanded="false"><%= t('navbar.categories') %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
                <li><%= link_to category.name, listings_path(category: category.name) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Manage Listings", seller_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
             aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <div align="center">
                  <li><p class="user"><strong><%= current_user.name %></strong></p></li>
                  <li><%= link_to t('navbar.user_profile'), user_registration_path %></li>
                  <li><%= link_to t('navbar.edit_user'), edit_user_registration_path %></li>
                  <li><%= link_to t('navbar.sales_history'), sales_path %></li>
                  <li><%= link_to t('navbar.purchases_history'), purchases_path %></li>

                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
            </div>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_slides.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("banner.jpg") %>
      <div class="carousel-caption">
       ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("banner-img5.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("banner4.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("organic-food-banner.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("FarmFresh_banner_1.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrganicMarketplace</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>

<%= render 'layouts/facebook' %>
<%= render 'layouts/header' %>
<div class="container">
  <%= render 'layouts/slides' %>
  <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "danger" %>alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" area-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
      <% end %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>